path_to_recording: 

pipeline:
  - TemporalAlignmentStep
  - SpatialAlignmentStep
  - JointAnglesStep
  - StepFinderStep
  - GaitParametersStep
  - TrajectoryStridesStep
  - JointAnglesStridesStep
  - RMSEStep


ProjectConfig:
  qualisys_model_info_path: C:\Users\aaron\Documents\GitHub\freemocap_validation\qualisys_markerset\qualisys_prosthetic_model_info.yaml
  freemocap_tracker: mediapipe_dlc
  conditions:
    ~:
      frames: []

TemporalAlignmentStep:
  start_frame: null
  end_frame: null
  qualisys_joint_weights_file: qualisys_joint_weights/prosthetic_joint_center_weights.yaml

SpatialAlignmentStep:
  markers_for_alignment:
    - left_heel
    - right_heel
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_shoulder
    - right_shoulder

  frames_to_sample: 20
  max_iterations: 100
  inlier_threshold: 40

JointAnglesStep:
  neutral_frames: []

StepFinderStep:
  sampling_rate: 30.0
  frames_of_interest: []

TrajectoryStridesStep:
  loop_over_conditions: False

JointAnglesStridesStep:
  loop_over_conditions: False

GaitParametersStep:
  loop_over_conditions: False
  sampling_rate: 30.0


RMSEStep:
  markers_for_comparison:
    - left_shoulder
    - right_shoulder
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_heel
    - right_heel
    - left_foot_index
    - right_foot_index
