pipeline:
  - TemporalAlignmentStep
  - SpatialAlignmentStep
  - RMSEStep


ProjectConfig:
  qualisys_model_info_path: C:\Users\aaron\Documents\GitHub\freemocap_validation\qualisys_markerset\qualisys_model_info.yaml
  freemocap_tracker: rtmpose

QualisysActorStep:
  model_info_path: C:\Users\aaron\Documents\GitHub\freemocap_validation\qualisys_markerset\qualisys_model_info.yaml

TemporalAlignmentStep:
  start_frame: 500
  end_frame: 1000

SpatialAlignmentStep:
  markers_for_alignment:
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_heel
    - right_heel
    - left_foot_index
    - right_foot_index
  
  frames_to_sample: 20
  max_iterations: 100
  inlier_threshold: 40

RMSEStep:
  variants:
    - 3d_xyz
    - rigid_3d_xyz

  start_frame: 440
  end_frame: 1000
  markers_for_comparison:
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_heel
    - right_heel
    - left_foot_index
    - right_foot_index
