from validation.components import QUALISYS_MARKERS, QUALISYS_START_TIME, QUALISYS_SYNCED_JOINT_CENTERS, FREEMOCAP_ACTOR, FREEMOCAP_TIMESTAMPS

REQUIRES = [FREEMOCAP_TIMESTAMPS, 
            QUALISYS_MARKERS, 
            QUALISYS_START_TIME,
            FREEMOCAP_ACTOR]

PRODUCES = [QUALISYS_SYNCED_JOINT_CENTERS]