from validation.components import QUALISYS_SYNCED_JOINT_CENTERS, FREEMOCAP_JOINT_CENTERS, POSITIONABSOLUTEERROR, POSITIONRMSE, VELOCITYRMSE, VELOCITYABSOLUTEERROR, FREEMOCAP_PARQUET

REQUIRES = [QUALISYS_SYNCED_JOINT_CENTERS, FREEMOCAP_JOINT_CENTERS, FREEMOCAP_PARQUET]
PRODUCES = [POSITIONABSOLUTEERROR,POSITIONRMSE, VELOCITYABSOLUTEERROR, VELOCITYRMSE]