from validation.components import QUALISYS_SYNCED_JOINT_CENTERS, FREEMOCAP_JOINT_CENTERS, POSITIONABSOLUTEERROR, POSITIONRMSE, VELOCITYRMSE, VELOCITYABSOLUTEERROR

REQUIRES = [QUALISYS_SYNCED_JOINT_CENTERS, FREEMOCAP_JOINT_CENTERS]
PRODUCES = [POSITIONABSOLUTEERROR,POSITIONRMSE, VELOCITYABSOLUTEERROR, VELOCITYRMSE]