from validation.components import QUALISYS_SYNCED_MARKER_DATA, QUALISYS_TRC, FREEMOCAP_JOINT_CENTERS, FREEMOCAP_TRC

REQUIRES = [QUALISYS_SYNCED_MARKER_DATA, FREEMOCAP_JOINT_CENTERS]
PRODUCES = [FREEMOCAP_TRC, QUALISYS_TRC]
