from validation.components import TRANSFORMATION_MATRIX, FREEMOCAP_PRE_SYNC_JOINT_CENTERS, FREEMOCAP_JOINT_CENTERS, FREEMOCAP_COM, QUALISYS_SYNCED_JOINT_CENTERS

REQUIRES = [FREEMOCAP_PRE_SYNC_JOINT_CENTERS, QUALISYS_SYNCED_JOINT_CENTERS]
PRODUCES = [TRANSFORMATION_MATRIX, FREEMOCAP_JOINT_CENTERS, FREEMOCAP_COM]
