path_to_recording: D:\validation\data\2026-01-30-JTM\2026-01-30_11-32-56_GMT-5_JTM_treadmill_2
pipeline:
  - TemporalAlignmentStep
  - SpatialAlignmentStep
  - JointAnglesStep
  - StepFinderStep
  - GaitParametersStep
  - TrajectoryStridesStep
  - JointAnglesStridesStep
  - RMSEStep

ProjectConfig:
  qualisys_model_info_path: C:\Users\aaron\Documents\GitHub\freemocap_validation\qualisys_markerset\qualisys_model_info.yaml
  freemocap_tracker: mediapipe
  conditions:
    overall:
      frames: [1400, 5400] 
    # speed_0_5:
    #   frames: [1500, 2100]
    # speed_1_0: 
    #   frames:  [2400, 3000]
    # speed_1_5: 
    #   frames:  [3500, 4100] 
    # speed_2_0: 
    #   frames:  [4700, 5300]

TemporalAlignmentStep: 
  start_frame: null
  end_frame: null
  qualisys_joint_weights_file: qualisys_joint_weights/validation_study_weights.yaml

SpatialAlignmentStep:
  markers_for_alignment:
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_heel
    - right_heel
    - left_foot_index
    - right_foot_index  

  frames_to_sample: 20
  max_iterations: 100
  inlier_threshold: 40

JointAnglesStep:
  neutral_frames: [640, 750]

StepFinderStep:
  sampling_rate: 30.0
  frames_of_interest: [1400,5400]  # e.g., [start_frame, end_frame] or null for entire recording

TrajectoryStridesStep:
  loop_over_conditions: True

JointAnglesStridesStep:
  loop_over_conditions: True

RMSEStep:
  loop_over_conditions: True
  markers_for_comparison:
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
    - left_heel
    - right_heel
    - left_foot_index
    - right_foot_index

GaitParametersStep:
  loop_over_conditions: True
  loop_over_conditions: True
  sampling_rate: 30.0
